import { AppShell } from "../../components/AppShell";
import { ArrowDownToLine, ArrowUpRight, CircleDollarSign, CreditCard, Download, TrendingUp, WalletCards } from "lucide-react";

export default function TutorEarnings() {
  return (
    <AppShell role="tutor" active="/profesor/zarada" eyebrow="Financije" title="Zarada i isplate" action={<button className="button button-outline button-small"><Download /> Izvezi izvještaj</button>}>
      <section className="earnings-overview"><div><span className="metric-icon coral"><CircleDollarSign /></span><p><small>Zarada u srpnju</small><strong>1.428,00 €</strong><em><TrendingUp /> +18,4% prema lipnju</em></p></div><div><span className="metric-icon mint"><WalletCards /></span><p><small>Sljedeća isplata</small><strong>486,20 €</strong><em>Petak, 24. srpnja</em></p></div><div><span className="metric-icon blue"><CreditCard /></span><p><small>Prosjek po satu</small><strong>17,00 €</strong><em>Nakon naknade</em></p></div></section>
      <div className="earnings-main-grid"><section className="dashboard-panel earnings-chart-panel"><div className="panel-heading"><div><span>PRIHOD</span><h3>Posljednjih 6 mjeseci</h3></div><select><option>Ukupna zarada</option></select></div><div className="large-bar-chart">{[["VEL",820],["OŽU",1010],["TRA",940],["SVI",1180],["LIP",1206],["SRP",1428]].map(([month,value]) => <div key={month}><span>{value} €</span><i style={{height:`${Number(value)/16}px`}} className={month === "SRP" ? "active" : ""} /><small>{month}</small></div>)}</div></section><section className="dashboard-panel payout-account"><div className="panel-heading"><div><span>ISPLATA</span><h3>Račun za isplatu</h3></div><CreditCard /></div><div className="bank-card"><small>IBAN</small><strong>HR12 •••• •••• 4821</strong><span>Zagrebačka banka · Ana Kovač</span></div><p><ArrowDownToLine /> Automatska tjedna isplata petkom</p><button>Uredi račun</button></section></div>
      <section className="dashboard-panel transaction-panel"><div className="panel-heading"><div><span>TRANSAKCIJE</span><h3>Nedavne aktivnosti</h3></div><button>Filtriraj</button></div><div className="transaction-head"><span>Datum</span><span>Učenik / opis</span><span>Bruto</span><span>Naknada</span><span>Neto</span><span>Status</span></div>{[["20. srp.","Mia Radić · Integrali","18,00 €","−2,70 €","15,30 €"],["19. srp.","Luka Perić · Derivacije","18,00 €","−2,70 €","15,30 €"],["18. srp.","Filip Kos · Matura A","20,00 €","−3,00 €","17,00 €"],["17. srp.","Tjedna isplata","","","−432,80 €"]].map((row,index) => <div className="transaction-row" key={row[0]+row[1]}><span>{row[0]}</span><span><i className={index === 3 ? "payout" : "lesson"}>{index === 3 ? <ArrowUpRight /> : <CircleDollarSign />}</i><strong>{row[1]}</strong></span><span>{row[2]}</span><span>{row[3]}</span><strong>{row[4]}</strong><em>{index === 3 ? "Isplaćeno" : "Dostupno"}</em></div>)}</section>
    </AppShell>
  );
}
