import Link from "next/link";
import { AppShell } from "../../../components/AppShell";
import { ArrowLeft, BookOpenCheck, BrainCircuit, Check, ChevronRight, Download, FileQuestion, Flame, Play, RotateCcw, Sparkles, Target, Video, WandSparkles } from "lucide-react";

export default function LessonPackPage() {
  return (
    <AppShell role="student" active="/ucenik/lekcije/derivacije" eyebrow="AI paket znanja · 18. srpnja 2026." title="Derivacije složenih funkcija" action={<button className="button button-outline button-small"><Download size={16} /> Preuzmi PDF</button>}>
      <div className="lesson-pack-layout">
        <nav className="lesson-pack-nav"><Link href="/ucenik"><ArrowLeft /> Sve lekcije</Link><a className="active" href="#sazetak">Sažetak</a><a href="#pojmovi">Ključni pojmovi</a><a href="#zadaci">Zadaci</a><a href="#kviz">Kviz</a><a href="#snimka">Snimka sata</a></nav>
        <main className="lesson-pack-main">
          <section className="pack-hero" id="sazetak"><div><span className="pack-chip"><Sparkles /> Generirano 3 min nakon sata</span><h2>Tvoj sat u jednom pogledu</h2><p>Na satu si usvojio lančano pravilo i derivaciju kompozicije. Najviše nesigurnosti ostalo je kod trigonometrijskih funkcija.</p></div><div className="mastery-card"><span>RAZUMIJEVANJE TEME</span><div className="mastery-ring"><strong>84%</strong></div><small>+12% nakon ovog sata</small></div></section>
          <section className="pack-section"><div className="pack-title"><span className="metric-icon blue"><BookOpenCheck /></span><div><small>AI SAŽETAK</small><h3>Što ste danas radili</h3></div></div><div className="summary-note"><p><strong>Glavna ideja.</strong> Kod derivacije složene funkcije prvo deriviraš vanjsku funkciju, a zatim rezultat množiš derivacijom unutarnje funkcije.</p><div className="formula">(f(g(x)))′ = f′(g(x)) · g′(x)</div><p><strong>Korak koji moraš zapamtiti.</strong> Nakon što deriviraš vanjsku funkciju, nemoj zaboraviti “unutarnji trag” — derivaciju onoga što se nalazi u zagradi.</p></div></section>
          <section className="pack-section" id="pojmovi"><div className="pack-title"><span className="metric-icon mint"><Target /></span><div><small>MAPA ZNANJA</small><h3>Ključni pojmovi</h3></div></div><div className="concept-cards"><div className="mastered"><span><Check /> USVOJENO</span><h4>Lančano pravilo</h4><p>Prepoznaješ vanjsku i unutarnju funkciju.</p></div><div className="mastered"><span><Check /> USVOJENO</span><h4>Kompozicija funkcija</h4><p>Ispravno zapisuješ f(g(x)).</p></div><div className="practice"><span><Flame /> VJEŽBAJ</span><h4>Trigonometrijske funkcije</h4><p>Još ponekad izostaviš unutarnju derivaciju.</p></div></div></section>
          <section className="pack-section" id="zadaci"><div className="pack-title"><span className="metric-icon coral"><WandSparkles /></span><div><small>PERSONALIZIRANA VJEŽBA</small><h3>Zadaci za tvoju slabu točku</h3></div></div><div className="task-list"><article><span>01</span><p>Izračunaj derivaciju funkcije <strong>f(x) = sin(4x³)</strong>.</p><button>Prikaži trag</button></article><article><span>02</span><p>Izračunaj derivaciju funkcije <strong>g(x) = cos²(2x)</strong>.</p><button>Prikaži trag</button></article><article><span>03</span><p>Odredi derivaciju funkcije <strong>h(x) = tan(√x)</strong>.</p><button>Prikaži trag</button></article></div><Link className="button button-navy" href="/ucenik/ai-mentor">Rješavaj uz AI Mentora <ChevronRight /></Link></section>
          <section className="pack-section" id="kviz"><div className="pack-title"><span className="metric-icon gold"><FileQuestion /></span><div><small>BRZA PROVJERA</small><h3>Kviz od 5 pitanja</h3></div></div><div className="quiz-card"><div><span><strong>5</strong><small>pitanja</small></span><span><strong>7 min</strong><small>procjena</small></span><span><strong>80%</strong><small>cilj</small></span></div><p>Kviz se prilagođava tvojim odgovorima. Ako pogriješiš, dobit ćeš kraće objašnjenje prije sljedećeg pitanja.</p><Link href="/ucenik/ai-mentor">Pokreni kviz <ChevronRight /></Link></div></section>
          <section className="pack-section" id="snimka"><div className="pack-title"><span className="metric-icon blue"><Video /></span><div><small>SNIMKA SATA</small><h3>Vrati se na ključni trenutak</h3></div></div><div className="recording-card"><div className="recording-screen"><button><Play fill="currentColor" /></button><span>42:18</span></div><div className="chapters"><strong>Automatska poglavlja</strong><button><span>04:22</span> Prepoznavanje složene funkcije</button><button className="active"><span>18:47</span> Lančano pravilo — objašnjenje</button><button><span>34:05</span> Greška kod sin(3x²)</button></div></div></section>
        </main>
        <aside className="lesson-pack-aside"><div className="pack-mentor"><div className="avatar avatar-coral">AK</div><span><small>MENTOR</small><strong>Ana Kovač</strong><em>Sljedeći sat · 23. srp.</em></span></div><div className="next-recommend"><BrainCircuit /><small>AI PREPORUKA</small><h3>Još 15 minuta danas</h3><p>Dovrši 3 ciljana zadatka kako bi temu podigao na 90%.</p><i><b style={{ width: "60%" }} /></i><span>2 od 3 završeno</span><Link href="/ucenik/ai-mentor">Nastavi vježbati <ChevronRight /></Link></div><div className="pack-streak"><RotateCcw /><span><strong>6 tjedana u nizu</strong><small>Nastavi i sutra za novi rekord.</small></span></div></aside>
      </div>
    </AppShell>
  );
}
