import Link from "next/link";
import { AppShell } from "../components/AppShell";
import { Activity, AlertTriangle, ArrowRight, BadgeCheck, CircleDollarSign, Eye, Radio, ShieldAlert, Sparkles, TrendingUp, Users, Video } from "lucide-react";

export default function AdminDashboard() {
  return (
    <AppShell role="admin" active="/admin" eyebrow="Platforma uživo" title="Command center" action={<span className="live-system"><i /> Svi sustavi operativni</span>}>
      <section className="ops-hero"><div><span className="ops-live"><Radio /> UŽIVO</span><h2>Platforma upravo povezuje<br /><strong>38 učenika i mentora.</strong></h2><p>21 aktivan sat · 17 rezervacija u sljedećih 60 min · 0 kritičnih incidenata</p></div><div className="live-map"><i className="node n1" /><i className="node n2" /><i className="node n3" /><i className="node n4" /><i className="node n5" /><i className="line l1" /><i className="line l2" /><i className="line l3" /><span><Activity /> 21 live</span></div></section>
      <section className="dashboard-metrics admin-metrics"><div><span className="metric-icon blue"><CircleDollarSign /></span><p><small>GMV ovaj mjesec</small><strong>148.240 €</strong><em>+21,8% MoM</em></p></div><div><span className="metric-icon coral"><TrendingUp /></span><p><small>Platformski prihod</small><strong>22.236 €</strong><em>15,0% take rate</em></p></div><div><span className="metric-icon mint"><Users /></span><p><small>Aktivni korisnici</small><strong>3.842</strong><em>1.126 ovaj tjedan</em></p></div><div><span className="metric-icon gold"><Video /></span><p><small>Održani sati</small><strong>9.883</strong><em>98,7% completion</em></p></div></section>
      <div className="ops-grid">
        <section className="dashboard-panel ops-growth"><div className="panel-heading"><div><span>CORE METRICS</span><h3>Rast platforme</h3></div><select><option>Zadnjih 30 dana</option></select></div><div className="ops-line-chart"><div className="chart-labels"><span>10k</span><span>7.5k</span><span>5k</span><span>2.5k</span><span>0</span></div><div className="growth-bars">{[18,22,20,28,32,30,38,41,46,43,52,58,55,66,63,71,76,73,84,92].map((height,index)=><i key={`${height}-${index}`} style={{height:`${height}%`}} />)}</div><div className="chart-dates"><span>21. lip.</span><span>28. lip.</span><span>5. srp.</span><span>12. srp.</span><span>21. srp.</span></div></div><div className="ops-kpis"><span><small>Konverzija pretraga → rezervacija</small><strong>18,7% <em>+2,1</em></strong></span><span><small>Ponovna rezervacija</small><strong>68,4% <em>+4,8</em></strong></span><span><small>Prosječna cijena sata</small><strong>15,00 € <em>+0,40</em></strong></span></div></section>
        <section className="dashboard-panel trust-queue"><div className="panel-heading"><div><span>TRUST & SAFETY</span><h3>Red za pregled</h3></div><span className="queue-count">7</span></div><div className="trust-health"><div className="health-ring"><strong>99.2%</strong></div><span><strong>Zdravlje platforme</strong><small>48.920 poruka analizirano danas</small></span></div><div className="incident-row high"><ShieldAlert /><span><strong>Pokušaj dijeljenja kontakta</strong><small>Chat · mentor ID #M-1842 · prije 4 min</small></span><button><Eye /></button></div><div className="incident-row medium"><AlertTriangle /><span><strong>Neuobičajeno otkazivanje</strong><small>5 otkazivanja · mentor ID #M-0917</small></span><button><Eye /></button></div><div className="incident-row low"><BadgeCheck /><span><strong>Verifikacija diplome</strong><small>3 nova profila čekaju pregled</small></span><button><ArrowRight /></button></div><Link href="/admin/sigurnost">Otvori trust & safety centar <ArrowRight /></Link></section>
      </div>
      <div className="ops-grid bottom">
        <section className="dashboard-panel live-lessons"><div className="panel-heading"><div><span>AKTIVNI SATI · UŽIVO</span><h3>Kvaliteta sesija</h3></div><span><i /> 21 aktivan</span></div><div className="live-lesson-head"><span>Sesija</span><span>Trajanje</span><span>Kvaliteta</span><span>AI status</span><span></span></div>{[["Ana K. ↔ Luka P.","42:18","Odlično","Transkripcija"],["Marko H. ↔ Mia R.","28:41","Dobro","Transkripcija"],["Lucija M. ↔ Nika B.","51:03","Odlično","Bilješke uživo"]].map((row,index) => <div className="live-lesson-row" key={row[0]}><span><i>{index===0?"AK":index===1?"MH":"LM"}</i><strong>{row[0]}</strong></span><span>{row[1]}</span><span><b className={index===1?"good":"excellent"} /> {row[2]}</span><span><Sparkles /> {row[3]}</span><button>•••</button></div>)}</section>
        <section className="dashboard-panel supply-panel"><div className="panel-heading"><div><span>MARKETPLACE</span><h3>Ponuda i potražnja</h3></div><Users /></div><div className="supply-alert"><AlertTriangle /><span><strong>Manjak mentora za Kemiju</strong><small>Potražnja 2,4× veća od dostupnosti ovaj tjedan.</small></span></div><div className="subject-balance"><p><span>Matematika</span><i><b style={{width:"88%"}} /></i><strong>0.9×</strong></p><p><span>Fizika</span><i><b style={{width:"73%"}} /></i><strong>1.2×</strong></p><p><span>Kemija</span><i><b className="coral" style={{width:"42%"}} /></i><strong>2.4×</strong></p><p><span>Engleski</span><i><b style={{width:"94%"}} /></i><strong>0.8×</strong></p></div><button>Pokreni kampanju za mentore <ArrowRight /></button></section>
      </div>
    </AppShell>
  );
}
