"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { Edit3, KeyRound, LoaderCircle, Search, ShieldCheck, UserCheck, Users, X } from "lucide-react";
import { AppShell } from "../../components/AppShell";
import { apiFetch } from "../../lib/api";

type User = { id:string; name:string; email:string; role:"student"|"tutor"|"admin"; status:"active"|"deactivated"; authProvider:string; createdAt:string };
const labels = { all:"Svi korisnici", active:"Aktivni", student:"Studenti", tutor:"Profesori", deactivated:"Deaktivirani" } as const;

export default function UserAdmin() {
  const [users,setUsers]=useState<User[]>([]); const [filter,setFilter]=useState<keyof typeof labels>("all"); const [query,setQuery]=useState(""); const [selected,setSelected]=useState<User|null>(null); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const load=async()=>{setLoading(true);try{const {data}=await apiFetch<User[]>("/admin/users");setUsers(data)}catch(e){setError(e instanceof Error?e.message:"Nije moguće učitati korisnike.")}finally{setLoading(false)}};
  useEffect(()=>{void Promise.resolve().then(load)},[]);
  const filtered=useMemo(()=>users.filter(u=>(filter==="all"||filter==="active"?filter==="all"||u.status==="active":filter===u.role||u.status==="deactivated")&&`${u.name} ${u.email}`.toLowerCase().includes(query.toLowerCase())),[users,filter,query]);
  const counts={all:users.length,active:users.filter(u=>u.status==="active").length,student:users.filter(u=>u.role==="student").length,tutor:users.filter(u=>u.role==="tutor").length,deactivated:users.filter(u=>u.status==="deactivated").length};
  const save=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setSaving(true);setError("");try{const {data}=await apiFetch<User>(`/admin/users/${selected.id}`,{method:"PATCH",body:JSON.stringify({...selected,password})});setUsers(v=>v.map(u=>u.id===data.id?data:u));setSelected(null);setPassword("")}catch(err){setError(err instanceof Error?err.message:"Spremanje nije uspjelo.")}finally{setSaving(false)}};
  return <AppShell role="admin" active="/superdmin/upravljanje" eyebrow="Superadmin · God mode" title="Korisnici" action={<button className="button button-outline button-small" onClick={load}>Osvježi podatke</button>}>
    <section className="user-admin-cards">{(["all","active","student","tutor","deactivated"] as const).map(key=><button key={key} className={filter===key?"selected":""} onClick={()=>setFilter(key)}><span>{key==="active"?<UserCheck/>:key==="tutor"?<ShieldCheck/>:<Users/>}</span><strong>{counts[key]}</strong><small>{labels[key]}</small></button>)}</section>
    <section className="user-admin-panel"><div className="user-admin-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Pretraži ime ili e-mail…"/></label><span>{filtered.length} rezultata · {labels[filter]}</span></div>{error&&!selected&&<div className="auth-error">{error}</div>}<div className="user-admin-list">{loading?<LoaderCircle className="spin"/>:filtered.map(user=><button key={user.id} onClick={()=>{setSelected({...user});setPassword("");setError("")}}><span className="user-avatar">{user.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span><strong>{user.name}</strong><small>{user.email} · {user.authProvider}</small></span><em className={`user-status ${user.status}`}>{user.status==="active"?"Aktivan":"Deaktiviran"}</em><i>{user.role==="tutor"?"Profesor":user.role==="student"?"Student":"Superadmin"}</i><Edit3/></button>)}</div></section>
    {selected&&createPortal(<div className="admin-modal-backdrop" onClick={()=>setSelected(null)}><form className="admin-user-modal" onSubmit={save} onClick={e=>e.stopPropagation()}><button type="button" className="modal-close" aria-label="Zatvori uređivanje korisnika" onClick={()=>{setSelected(null);setPassword("");setError("")}}><X/></button><div className="admin-modal-content"><span className="step-kicker">UREDI KORISNIKA</span><h2>{selected.name}</h2><label className="form-label">Ime i prezime<input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value})}/></label><label className="form-label">E-mail<input type="email" value={selected.email} onChange={e=>setSelected({...selected,email:e.target.value})}/></label><div className="form-two"><label className="form-label">Uloga<select value={selected.role} onChange={e=>setSelected({...selected,role:e.target.value as User["role"]})}><option value="student">Student</option><option value="tutor">Profesor</option><option value="admin">Superadmin</option></select></label><label className="form-label">Status<select value={selected.status} onChange={e=>setSelected({...selected,status:e.target.value as User["status"]})}><option value="active">Aktivan</option><option value="deactivated">Deaktiviran</option></select></label></div><label className="form-label"><span><KeyRound/> Nova lozinka <small>neobavezno</small></span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Ostavi prazno za zadržavanje postojeće"/></label>{error&&<div className="auth-error">{error}</div>}</div><div className="admin-modal-actions"><button type="button" className="button button-ghost" onClick={()=>{setSelected(null);setPassword("");setError("")}}>Odustani</button><button className="button button-coral" disabled={saving}>{saving?<LoaderCircle className="spin"/>:"Spremi promjene"}</button></div></form></div>,document.body)}
  </AppShell>;
}
