import Link from "next/link";
import { AppShell } from "../components/AppShell";
import { ArrowRight, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, MessageCircle, MoreHorizontal, Play, Sparkles, Star, TrendingUp, Video } from "lucide-react";

export default function TutorDashboard() {
  return (
    <AppShell role="tutor" active="/profesor" eyebrow="Utorak, 21. srpnja" title="Dobro jutro, Ana" action={<Link className="button button-coral button-small" href="/profesor/kalendar">＋ Dodaj dostupnost</Link>}>
      <section className="tutor-dashboard-hero"><div><span className="dashboard-chip"><Video /> SLJEDEĆI SAT ZA 2 H 14 MIN</span><h2>Luka Perić · Derivacije</h2><p>18:30 – 19:30 · 24. zajednički sat</p><div><Link className="button button-coral" href="/ucenik/sat/matematika-derivacije"><Play size={16} /> Pripremi učionicu</Link><button className="button button-ghost-dark"><MessageCircle size={16} /> Pošalji poruku</button></div></div><div className="prep-insight"><Sparkles /><span><small>AI PRIPREMA ZA VAS</small><strong>Luka često preskače unutarnju derivaciju</strong><p>Predložena su 3 primjera i jedan dijagnostički zadatak.</p><button>Otvori pripremu <ChevronRight /></button></span></div></section>
      <section className="dashboard-metrics tutor-metrics"><div><span className="metric-icon blue"><CalendarDays /></span><p><small>Sati ovaj mjesec</small><strong>84</strong><em>+12 prema lipnju</em></p></div><div><span className="metric-icon coral"><CircleDollarSign /></span><p><small>Zarada</small><strong>1.428 €</strong><em>+18,4% ovaj mjesec</em></p></div><div><span className="metric-icon gold"><Star /></span><p><small>Ocjena</small><strong>4.98</strong><em>184 recenzije</em></p></div><div><span className="metric-icon mint"><TrendingUp /></span><p><small>Ponovne rezervacije</small><strong>95%</strong><em>Elite standard</em></p></div></section>
      <div className="tutor-dashboard-grid">
        <section className="dashboard-panel today-schedule"><div className="panel-heading"><div><span>DANAS · 4 SATA</span><h3>Tvoj raspored</h3></div><Link href="/profesor/kalendar">Cijeli kalendar <ChevronRight /></Link></div>{[
          ["16:00", "Mia Radić", "Integrali · 60 min", "MR", "done"], ["18:30", "Luka Perić", "Derivacije · 60 min", "LP", "next"], ["20:00", "Filip Kos", "Priprema za maturu · 60 min", "FK", ""],
        ].map(([time,name,topic,initials,state]) => <div className={`schedule-row ${state}`} key={time}><span className="schedule-time">{time}</span><span className="mini-avatar">{initials}</span><span><strong>{name}</strong><small>{topic}</small></span>{state === "done" ? <em><Check /> Održano</em> : state === "next" ? <Link href="/ucenik/sat/matematika-derivacije">Pripremi <ArrowRight /></Link> : <button><MoreHorizontal /></button>}</div>)}<div className="open-slot"><Clock3 /><span><strong>19:30 – 20:00</strong><small>Pauza između sati</small></span></div></section>
        <section className="dashboard-panel reputation-card-panel"><div className="panel-heading"><div><span>TVAŠ PROFIL</span><h3>Elite reputacija</h3></div><span className="elite-mini"><Sparkles /> ELITE</span></div><div className="reputation-score-ring"><strong>96</strong><small>/100</small></div><p>U top 3% ste mentora za matematiku. Još 4 odgovora unutar 10 min održavaju vaš Elite status.</p><div className="rep-bars"><div><span>Ocjena</span><i><b style={{ width: "98%" }} /></i><strong>4.98</strong></div><div><span>Pouzdanost</span><i><b style={{ width: "100%" }} /></i><strong>100%</strong></div><div><span>Odgovor</span><i><b style={{ width: "92%" }} /></i><strong>8 min</strong></div></div><Link href="/profesori/ana-kovac">Pogledaj javni profil <ChevronRight /></Link></section>
      </div>
      <div className="tutor-dashboard-grid bottom">
        <section className="dashboard-panel student-insights"><div className="panel-heading"><div><span>AI UVIDI</span><h3>Učenici kojima treba pažnja</h3></div><Sparkles /></div><div><span className="mini-avatar">MP</span><p><strong>Marina P.</strong><small>Rezultat kviza pao je 18% u zadnja 2 tjedna.</small></p><button>Pregledaj</button></div><div><span className="mini-avatar">FK</span><p><strong>Filip K.</strong><small>Nije dovršio zadatke nakon zadnja 2 sata.</small></p><button>Pošalji poticaj</button></div></section>
        <section className="dashboard-panel payout-panel"><div className="panel-heading"><div><span>SLJEDEĆA ISPLATA</span><h3>Petak, 24. srpnja</h3></div><CircleDollarSign /></div><strong>486,20 €</strong><p>28 održanih sati · naknada platforme uračunata</p><Link href="/profesor/zarada">Detalji zarade <ChevronRight /></Link></section>
      </div>
    </AppShell>
  );
}
